- - - # settings for collection
- settings:
  default_lang        : en
  base_url            : https://data.participatory-archives.ch/
  pia_api_uri         : https://json.participatory-archives.ch/api/v1/collections
  pia_api_include     : 
  page_size           : 100
  directory           : set/
  a_collection        : data/a_collection
  b_mapped            : data/b_mapped
  c_linked_art        : data/c_linked_art
  template            : template.jsonnet
...